CREATE TABLE TBL_MEMBER_SKILL(
    ID NUMBER CONSTRAINT MEMBER_POSSESSED_TECHNOLOGY PRIMARY KEY,
    TECHNOLOGY_NAME VARCHAR2(255),
    PROFICIENCY VARCHAR2(255),
    EXPERIENCE VARCHAR2(255),
    MEMBER_ID NUMBER NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_MEMBER_P_TECHNOLOGY_MEMBER FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID)
);