CREATE TABLE TBL_ATTACHMENT (
    ID NUMBER CONSTRAINT PK_TBL_ATTACHMENT PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR(255), -- 첨부파일 경로
    FILE_TYPE VARCHAR2(50),
    FILE_SIZE NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ATTACHMENT_POST FOREIGN KEY(POST_ID)
    REFERENCES TBL_POST(ID)
);