CREATE TABLE TBL_POST(
    ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
    POST_TITLE VARCHAR2(255) NOT NULL,
    POST_CONTENT VARCHAR2(255) NOT NULL,
    POST_TYPE NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    POST_VIEW NUMBER DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
    REFERENCES TBL_USER(ID)
);