CREATE TABLE TBL_PROJECT_POST(
    ID NUMBER CONSTRAINT PK_PROJECT_POST PRIMARY KEY,
    STUDENT_MAJOR VARCHAR2(255),
    PROJECT_FIELD VARCHAR2(255),
    PROJECT_PROFIT VARCHAR2(255),
    PROJECT_PERIOD VARCHAR2(255),
    PROJECT_DEADLINE VARCHAR2(255) NOT NULL ,
    PROJECT_START_DATE VARCHAR2(255) NOT NULL,
    PROJECT_SCHEDULE VARCHAR2(255) NOT NULL ,
    PROJECT_REQUIREMENT VARCHAR2(255),
    CONSTRAINT FK_PROJECT_POST_POST FOREIGN KEY(ID)
    REFERENCES TBL_POST(ID)
);

DROP TABLE TBL_PROJECT_POST;

SELECT * FROM TBL_PROJECT_POST;