CREATE TABLE TBL_PROJECT_POST(
    ID NUMBER CONSTRAINT PK_PROJECT_POST PRIMARY KEY,
    PROJECT_FIELD VARCHAR2(255),
    PROJECT_REQUIREMENT VARCHAR2(255),
    CONSTRAINT FK_PROJECT_POST_POST FOREIGN KEY(ID)
    REFERENCES TBL_POST(ID)
);

SELECT * FROM TBL_PROJECT_POST;