CREATE TABLE TBL_THESIS_POST(
    ID NUMBER CONSTRAINT PK_THESIS_POST PRIMARY KEY,
    RESEARCH_FIELD VARCHAR2(255),
    RESEARCH_REQUIREMENT VARCHAR2(255),
    CONSTRAINT FK_THESIS_POST_POST FOREIGN KEY(ID)
    REFERENCES TBL_POST(ID)
);

SELECT * FROM TBL_THESIS_POST;

CREATE SEQUENCE SEQ_THESIS_POST;