CREATE TABLE TBL_THESIS_POST(
    ID NUMBER CONSTRAINT PK_THESIS_POST PRIMARY KEY,
    PROFESSOR_MAJOR VARCHAR2(255),
    RESEARCH_FIELD VARCHAR2(255),
    RESEARCH_PROFIT VARCHAR2(255),
    RESEARCH_PERIOD VARCHAR2(255),
    RESEARCH_DEADLINE VARCHAR2(255),
    RESEARCH_START_DATE VARCHAR2(255),
    RESEARCH_SCHEDULE VARCHAR2(255),
    RESEARCH_REQUIREMENT VARCHAR2(255),
    CONSTRAINT FK_THESIS_POST_POST FOREIGN KEY(ID)
    REFERENCES TBL_POST(ID)
);

DROP TABLE TBL_THESIS_POST;