CREATE TABLE TBL_FREE_POST(
        ID NUMBER CONSTRAINT PK_FREE_POST PRIMARY KEY,
        CONSTRAINT FK_FREE_POST_POST FOREIGN KEY(ID)
        REFERENCES TBL_POST(ID)
);

SELECT * FROM TBL_FREE_POST;